### ISSUE TITLE
ステータスチェックを１つに絞れるような仕組みを導入

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#271]
## 概要

ステータスチェックを１に絞るためには、次のようにすべてのチェックジョブの結果をまとめるジョブを作る必要がある。

```yaml
  status-check:
    runs-on: ubuntu-22.04
    needs:
      - check-xxx
      - check-yyy
      - check-zzz
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
```

このようにするためにはワークフローからすべてのチェックジョブを呼び出す必要がある。

１つのワークフローファイルにジョブをまとめようとすると記述量が多くなってしまい可読性が低下してしまうため、Reusable Workflows として設定する。

## 参考

- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/main/.github/workflows/check-pr.yaml
- https://docs.github.com/ja/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
